In [1]:
import numpy as np
import pandas as pd

In [2]:
# data frames data structure: basically a table

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [9]:
df = pd.DataFrame(data)
df

         0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [10]:
# pd.DataFrame(dataset) frames the data
# if we just create it with the data, it dosent know what columns mean, but we can do this..

In [11]:
df = pd.DataFrame(data, columns = columns) #columns = columns variable 
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [13]:
df.head(n=2) # gives first n amount of rows

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [14]:
# every column in the dataframe is called a series, if we want to access a specific series, we do..

In [15]:
df.Make # gives the column make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [16]:
df['Make'] # same thing, just useful if you have like for example the 'Engine HP' column since it has a space in the name

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [17]:
df[['Make','Model','MSRP']] # a list inside the brackets

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [18]:
# if we want to add a column, we do this:

In [20]:
df['id'] = [1,2,3,4,5] # id column
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [21]:
df['id'] = [10,20,30,40,50] # replace col
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [28]:
del df['Model'] # i deleted make beforehand too
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr SUV  34450
4  2017      261.0                 6            MANUAL        Pickup  32340

In [29]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [30]:
df.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [31]:
# 0 1 2 3 4 is the indexes

In [32]:
df.loc[1] # loc is location, it gives the row of the specific index

Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [33]:
df.loc[[1,2]]

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990

In [35]:
df.index = ['a','b','c','d','e']

In [36]:
df.Year

a    1991
b    2017
c    2010
d    2017
e    2017
Name: Year, dtype: int64

In [37]:
# indexes are what i set them to now

In [38]:
# but you can still get rows from the numerical base indexes with iloc

In [39]:
df.iloc[[1,2,4]]

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
b  2017        NaN                 4         AUTOMATIC         Sedan  27150
c  2010      218.0                 4            MANUAL   convertible  54990
e  2017      261.0                 6            MANUAL        Pickup  32340

In [40]:
 df.reset_index() # reset index to numerical and creates a new index column

,index,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,a,1991,138.0,4,MANUAL,sedan,2000
1,b,2017,NaN,4,AUTOMATIC,Sedan,27150
2,c,2010,218.0,4,MANUAL,convertible,54990
3,d,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,e,2017,261.0,6,MANUAL,Pickup,32340

In [44]:
df = df.reset_index(drop = True) # resets index AND drops index column
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr SUV  34450
4  2017      261.0                 6            MANUAL        Pickup  32340

In [45]:
# element-wise operations now

In [47]:
df['Engine HP'] / 100   # divides engine hp col by 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [48]:
# NaN means missing number

In [49]:
# you can do any arithematic operation basically, like multiply or divide or add.. wtv

In [50]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [51]:
# things of this nature can all be done, this is an example of filtering

In [52]:
#more on filtering...

In [59]:
df[
    df['Year'] >= 2015
]
# returns the True values in a new dataframe

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
3  2017      194.0                 4         AUTOMATIC       4dr SUV  34450
4  2017      261.0                 6            MANUAL        Pickup  32340

In [61]:
# combination filtering:
df[
    (df['Year'] >= 2015) & (df['Transmission Type'] == 'AUTOMATIC')
]

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
3  2017      194.0                 4         AUTOMATIC       4dr SUV  34450

In [62]:
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         Sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr SUV  34450
4  2017      261.0                 6            MANUAL        Pickup  32340

In [63]:
df.Vehicle_Style

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [64]:
df.Vehicle_Style.str.lower() # makes everything in the column lowercase

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [65]:
df.Vehicle_Style.str.replace(' ', '_') # replace spaces with underscores

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [69]:
df['Vehicle_Style'] = df.Vehicle_Style.str.replace(' ', '_').str.lower()
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr_suv  34450
4  2017      261.0                 6            MANUAL        pickup  32340

In [70]:
# summarizing operations now

In [71]:
df.MSRP

0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64

In [72]:
df.MSRP.min

<bound method Series.min of 0     2000
1    27150
2    54990
3    34450
4    32340
Name: MSRP, dtype: int64>

In [73]:
# ...etc same as numpy. can do .max, .std, etc

In [74]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [75]:
# gives a bunch of useful statistics all in one

In [76]:
df.describe() # does it for whole dataframe

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [77]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [78]:
# rounds to 2 decimal

In [80]:
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr_suv  34450
4  2017      261.0                 6            MANUAL        pickup  32340

In [81]:
df.Year.nunique() # gives the number of unique values in the series

3

In [83]:
df.nunique() # gives for whole dataframe

Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [84]:
# missing values now, NaN

In [85]:
df.isnull() # t/f if there is null value

    Year  Engine HP  Engine Cylinders  Transmission Type  Vehicle_Style   MSRP
0  False      False             False              False          False  False
1  False       True             False              False          False  False
2  False      False             False              False          False  False
3  False      False             False              False          False  False
4  False      False             False              False          False  False

In [87]:
df.isnull().sum() # gives num of missing values per series

Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [89]:
# Grouping
df

   Year  Engine HP  Engine Cylinders Transmission Type Vehicle_Style   MSRP
0  1991      138.0                 4            MANUAL         sedan   2000
1  2017        NaN                 4         AUTOMATIC         sedan  27150
2  2010      218.0                 4            MANUAL   convertible  54990
3  2017      194.0                 4         AUTOMATIC       4dr_suv  34450
4  2017      261.0                 6            MANUAL        pickup  32340

In [90]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [91]:
# groups by the transmission type column, and for each group we want to find the max msrp. so automatic max and manual max. 
# can do other functions with this like .std or .min, etc..

In [92]:
# getting numpy arrays:

In [93]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [94]:
# returns the underlying numpy array

In [97]:
df.to_dict(orient = 'records')

[{'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

In [98]:
# converts dataframe into the OG dictionary. orient is to structure the dictionary into different like things. 
# records is one, dict is the common one, there are others